# Site settings
title: Blog | Joey F. Poon
header-img: img/home-bg.jpg
email: joey@joeypoon.com
description: "A Programmer's Adventures"
baseurl: "/blog"
url: "joeypoon.com"
twitter_username: joeyfpoon
github_username:  joeypoon
linkedin_username: joeypoon

# Build settings
gems: [jekyll-paginate]
markdown: kramdown
highlighter: pygments
permalink: :title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
